PackageIdentifier: kobaltgit.StashIt
PackageVersion: 1.4.0
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - silentWithProgress
  - interactive
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/kobaltgit/StashIt/releases/download/v1.4.0/StashIt_1.4.0_x64-setup.exe
    InstallerSha256: 0EB9228743515C625BCD55FB67C8649DD967B83E7C52E55DA3F2D931809431B4
ManifestType: installer
ManifestVersion: 1.6.0
