name: stashit_website
description: "Официальный сайт StashIt — Kobalt Tools"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  kobalt_ui:
    git:
      url: https://github.com/kobaltgit/kobalt_ui.git
      ref: main

dependency_overrides:
  kobalt_ui:
    path: ../../kobalt_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/